### ISSUE TITLE
Redirection de flux

### ISSUE THREAD

**Issue by Malik-Fleury** [HE-Arc/Bash-to-C#8]
Implémentation de la redirection de flux:

- stdout
- stderr
- file

**Comment by JolieKimy** [comment]
https://stackoverflow.com/questions/39002052/how-i-can-print-to-stderr-in-c

use `fprintf(stdout, "%s", "Olaaaa");`

**Comment by Malik-Fleury** [comment]
Fonctionnalité pas mise en place.
